[package]
name = "partprobe-geometry-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
partprobe-geometry-core.workspace = true
partprobe-geometry-import.workspace = true
serde_json.workspace = true

[dev-dependencies]
partprobe-domain.workspace = true

[lints]
workspace = true
