[package]
name = "partprobe-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[target.'cfg(unix)'.dependencies]
close_fds.workspace = true
rustix.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Pipes",
    "Win32_System_Threading",
] }

[lints.rust]
unsafe_code = "deny"
