[package]
name = "partprobe-geometry-import"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
partprobe-domain.workspace = true
partprobe-geometry-core.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
